Make run-test fail if output-path is too long
Long output-path in no prebuild mode leads to silent fallback to
interpreter in dalvikvm.

This change ensures that we handle this situation by failing the
test.

Bug: 31597671
Test: m test-art-run-test -j
Change-Id: I19a7cee788760a81c9395be1252b2edab0db39f7

diff --git a/test/etc/run-test-jar b/test/etc/run-test-jar
--- a/test/etc/run-test-jar
+++ b/test/etc/run-test-jar
@@ -404,6 +404,18 @@ if [ "$HOST" = "n" ]; then
   fi
 fi
 
+# Prevent test from silently falling back to interpreter in no-prebuild mode. This happens
+# when DEX_LOCATION path is too long, because vdex/odex filename is constructed by taking
+# full path to dex, stripping leading '/', appending '@classes.vdex' and changing every
+# remaining '/' into '@'. Only checking in host mode because target paths are always short.
+if [ "$HOST" = "y" ]; then
+  VDEX_PATH="${DEX_LOCATION#/}/$TEST_NAME.jar@classes.vdex"
+  if [ ${#VDEX_PATH} -gt $(getconf NAME_MAX $DEX_LOCATION) ]; then
+      echo  "Dex location path too long."
+      exit 1
+  fi
+fi
+
 dex2oat_cmdline="true"
 mkdir_locations="${DEX_LOCATION}/dalvik-cache/$ISA"
 strip_cmdline="true"
