Do not execute OAT files that require app images that cannot be loaded
This change creates a new requires-image flag in the OAT header, which
is set when the file was created with an image (app image, etc.). If
this flag is set, we will not load the OAT file as executable if the
image could not be loaded.

Going forward, this allows the compiler to assume there will be an app
image when an app image is generated and in some cases generate better
code.

Note that we still must load the OAT file, because there will not always
be another way to access the underlying DEX files.

Revert submission 1298633-revert-155218105

Reason for revert: Fixing tests and relanding
Reverted Changes:
I701c91d5b:Revert "Disable ART run-test 2231-oat-require-app-...
Ic5cda4c75:Revert "Reject OAT file in speed-profile if app im...

Bug: 38313278
Test: ./test/run-test --host --64 2231-oat-require-app-image
Test: atest android.server.wm.MultiDisplaySecurityTests#testDisplayHasAccess_UIDCanPresentOnPrivateDisplay android.classloaders.cts.UsesLibraryHostTest#testUsesLibrary_full
Change-Id: I52cca033fa8e2e6de86514c833798c3d99b99477

diff --git a/test/etc/run-test-jar b/test/etc/run-test-jar
--- a/test/etc/run-test-jar
+++ b/test/etc/run-test-jar
@@ -86,6 +86,7 @@ TEST_DM="n"
 TEST_IS_NDEBUG="n"
 APP_IMAGE="y"
 SECONDARY_APP_IMAGE="y"
+REMOVE_APP_IMAGE="n"
 SECONDARY_CLASS_LOADER_CONTEXT=""
 SECONDARY_COMPILATION="y"
 JVMTI_STRESS="n"
@@ -246,6 +247,9 @@ while true; do
         shift
     elif [ "x$1" = "x--no-app-image" ]; then
         APP_IMAGE="n"
+        shift
+    elif [ "x$1" = "x--remove-app-image" ]; then
+        REMOVE_APP_IMAGE="y"
         shift
     elif [ "x$1" = "x--no-secondary-app-image" ]; then
         SECONDARY_APP_IMAGE="n"
@@ -884,6 +888,7 @@ profman_cmdline="true"
 dex2oat_cmdline="true"
 vdex_cmdline="true"
 dm_cmdline="true"
+rm_app_image_cmdline="true"
 mkdir_locations="${DEX_LOCATION}/dalvik-cache/$ISA"
 strip_cmdline="true"
 sync_cmdline="true"
@@ -966,8 +971,9 @@ function write_dex2oat_cmdlines {
     $enable_app_image && [ "$SECONDARY_APP_IMAGE" = "y" ] || enable_app_image=false
   fi
 
+  local app_image_file="$DEX_LOCATION/oat/$ISA/$name.art"
   local app_image=""
-  $enable_app_image && app_image="--app-image-file=$DEX_LOCATION/oat/$ISA/$name.art --resolve-startup-const-strings=true"
+  $enable_app_image && app_image="--app-image-file=$app_image_file --resolve-startup-const-strings=true"
 
   local dex2oat_binary
   dex2oat_binary=${DEX2OAT_DEBUG_BINARY}
@@ -1006,6 +1012,10 @@ function write_dex2oat_cmdlines {
     dex2oat_cmdline="${dex2oat_cmdline} --output-vdex=$DEX_LOCATION/oat/$ISA/primary.vdex"
     dm_cmdline="zip -qj $DEX_LOCATION/oat/$ISA/$name.dm $DEX_LOCATION/oat/$ISA/primary.vdex"
     vdex_cmdline="${dex2oat_cmdline} ${VDEX_ARGS} --dump-timings --dm-file=$DEX_LOCATION/oat/$ISA/$name.dm"
+  fi
+
+  if [ "$REMOVE_APP_IMAGE" = "y" ]; then
+    rm_app_image_cmdline="rm ${app_image_file}"
   fi
 }
 
@@ -1257,6 +1267,7 @@ if [ "$HOST" = "n" ]; then
              $dm_cmdline && \
              $vdex_cmdline && \
              $strip_cmdline && \
+             $rm_app_image_cmdline && \
              $sync_cmdline && \
              $timeout_prefix $dalvikvm_cmdline"
 
@@ -1346,7 +1357,7 @@ else
         echo EXPORT $var=${!var}
       done
       echo "$(declare -f linkdirs)"
-      echo "mkdir -p ${mkdir_locations} && $setupapex_cmdline && $installapex_cmdline && $linkroot_cmdline && $linkroot_overlay_cmdline && $profman_cmdline && $dex2oat_cmdline && $dm_cmdline && $vdex_cmdline && $strip_cmdline && $sync_cmdline && $cmdline"
+      echo "mkdir -p ${mkdir_locations} && $setupapex_cmdline && $installapex_cmdline && $linkroot_cmdline && $linkroot_overlay_cmdline && $profman_cmdline && $dex2oat_cmdline && $dm_cmdline && $vdex_cmdline && $strip_cmdline && $rm_app_image_cmdline && $sync_cmdline && $cmdline"
     fi
 
     cd $ANDROID_BUILD_TOP
@@ -1369,6 +1380,7 @@ else
     eval "$dm_cmdline" || { echo "Dex2oat failed." >&2 ; exit 2; }
     eval "$vdex_cmdline" || { echo "Dex2oat failed." >&2 ; exit 2; }
     $strip_cmdline || { echo "Strip failed." >&2 ; exit 3; }
+    $rm_app_image_cmdline || { echo "Failed to remove app image."; exit 5;}
     $sync_cmdline || { echo "Sync failed." >&2 ; exit 4; }
 
     if [ "$CREATE_RUNNER" = "y" ]; then
