Fix ThreadStress run-script's exit status.
Script test/004-ThreadStress/run executes the ThreadStress test
twice: the first time as a normal run, the second time in
locks-only mode with stack-dump lock profiling. However, if the
first run failed but the second did not, the script would return
an exit status of 0, which would hide the former failure. This
change ensure we return the first failing exit status, if any.

Test: art/test/testrunner/testrunner.py -t 004-ThreadStress
Change-Id: I5e4e4cc7d9311fe15637ea2f5248a0e9f2432d61

diff --git a/test/004-ThreadStress/run b/test/004-ThreadStress/run
--- a/test/004-ThreadStress/run
+++ b/test/004-ThreadStress/run
@@ -16,7 +16,17 @@
 
 # Enable lock contention logging.
 ${RUN} --runtime-option -Xlockprofthreshold:10 "${@}"
+return_status1=$?
 
 # Run locks-only mode with stack-dump lock profiling. Reduce the number of total operations from
 # the default 1000 to 100.
-${RUN} --runtime-option -Xlockprofthreshold:10 --runtime-option -Xstackdumplockprofthreshold:20 "${@}" Main --locks-only -o 100
+${RUN} --runtime-option -Xlockprofthreshold:10 --runtime-option -Xstackdumplockprofthreshold:20 \
+  "${@}" Main --locks-only -o 100
+return_status2=$?
+
+# Make sure we don't silently ignore a failure from the first command.
+if [ x$return_status1 != x0 ]; then
+  exit $return_status1
+else
+  exit $return_status2
+fi
